### ISSUE TITLE
RuntimeError: cublas runtime error : unknown error

### ISSUE THREAD

**Issue by minbeomkim** [doc2dial/sharedtask-dialdoc2021#7]
First, our desktop is

Ubuntu 20.04.3 LTS
Cuda 11.0
nvidia-graphic 470.57.02
GeForce 1080 Ti
pytorch 1.7.1
python 3.7

And we got

***** Running training *****
  Num examples = 70522
  Num Epochs = 5
  Instantaneous batch size per device = 15
  Total train batch size (w. parallel, distributed & accumulation) = 60
  Gradient Accumulation steps = 2
  Total optimization steps = 5875
  0%|                                                  | 0/5875 [00:00<?, ?it/s]Traceback (most recent call last):
  File "run_qa.py", line 496, in <module>
    main()
  File "run_qa.py", line 458, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/transformers/trainer.py", line 888, in train
    tr_loss += self.training_step(model, inputs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/transformers/trainer.py", line 1248, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/transformers/trainer.py", line 1277, in compute_loss
    outputs = model(**inputs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 1771, in forward
    return_dict=return_dict,
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 968, in forward
    return_dict=return_dict,
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 566, in forward
    output_attentions,
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 460, in forward
    past_key_value=self_attn_past_key_value,
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 393, in forward
    output_attentions,
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/minbeomkim/miniconda3/envs/test/lib/python3.7/site-packages/transformers/models/bert/modeling_bert.py", line 290, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: cublas runtime error : unknown error at /opt/conda/conda-bld/pytorch_1607370156314/work/aten/src/THC/THCBlas.cu:225

  0%|                                                  | 0/5875 [00:02<?, ?it/s]
./run_qa.sh: line 23: 66030 Segmentation fault      (core dumped) 

error.

Could you help me with some advices??

Thankyou

**Comment by minbeomkim** [comment]
I re-install cudatoolkit with 10.2 ver, then i resolve this problem.
